client/src/pages/Home.js, package-lock.json, package.json
Description
I have installed Material UI to the repo and I have added a facebook link.
Fixes #19 
- [ ✅] My code follows the style guidelines of this project
- [ ✅ ] I have carefully reviewed my own code
=> #19-facebook-link-karleen

client/src/App.js, client/src/Components/Header.jsx, client/src/pages/Home.jsx
Placeholder for Header component
Name your PR like this: #33 Epic: Landing Page-Header Component Placeholder
Placeholder for Header
Fixes #33
=> Header Component

client/src/pages/Home.jsx
=> twitter-icon

client/src/Components/Header.jsx, client/src/customHooks/useAuth.js
=> apply changes as recommended

client/src/App.js, client/src/Components/Footer.jsx, client/src/Components/Header.jsx, client/src/customHooks/useAuth.js, client/src/pages/ContactUs.jsx, client/src/pages/Dashboard.jsx, client/src/pages/Home.jsx, server/api.js
=> Hengameh- Create React Library for handling a user#44

client/src/customHooks/useAuth.js, client/src/pages/Dashboard.jsx
=> #50-Add Sign Out Button-Hengameh

client/src/Components/Header.jsx, client/src/index.html, client/src/pages/Dashboard.jsx, package-lock.json, package.json, server/api.js, server/controller/apiController.js, server/sequelize/config/config.js, server/sequelize/migrations/20230804001235-create-users-table.js, server/sequelize/migrations/20230804001548-create-tokens-table.js, server/sequelize/models/index.js, server/sequelize/models/tokens.js, server/sequelize/models/users.js
Sequelize setup done.
Fixes #42
=> #42-Sequelize-Farzaneh

client/src/App.js, client/src/Components/Hero.jsx, client/src/Mui-Components/Buttons.jsx, client/src/Mui-Components/ProductHeroLayout.jsx, client/src/Mui-Components/Typography.jsx
Created the Hero Component for Book Me. Image with text and register button
Fixes #61
=> 61- Hero Component using MUI- Tony Arora

client/src/pages/Home.jsx, client/src/pages/StaticGrid.css, client/src/pages/StaticGrid.jsx
=> #62- Front End static grid showcasing various services-Hengameh

client/src/Mui-Components/HomeCardGrid.jsx, client/src/pages/Home.jsx
Add  ui to card component and grid component for homepage
Fixes #63
=> add home card grid and component

client/src/index.html, server/api.js, server/controller/apiController.js, server/sequelize/config/config.js, server/sequelize/migrations/20230809084350-create-provider.js, server/sequelize/models/index.js, server/sequelize/models/provider.js
created Provider Model and function to create a Provider.
#79 
Fixes #79
=> created provider model and added create provider function

client/src/Components/Hero.jsx, client/src/pages/Home.jsx, server/api.js, server/controller/apiController.js, server/sequelize/config/config.js
Bug fixed, User can have many tokens.
Fixes #77
=> Farzaneh bug

client/src/App.js, client/src/Components/Header.jsx, client/src/pages/Subscription.jsx
Subscription component added. Become a provider goes to subsciption first and then to sign up form
Fixes #78
=> 78-Subscription Component- tony arora

client/src/App.js, client/src/Components/Newsletter.jsx, client/src/Mui-Components/SnackBar.jsx, client/src/Mui-Components/TextField.jsx, client/src/pages/Home.jsx, client/src/pages/Newsletter.jsx
Create the NewsLetter signup form component and incorporate it on the Home Page
Fixes #74
=> 74-Newsletter-Tony Arora

client/src/App.js, client/src/Components/Header.jsx, client/src/Components/Sidebar.jsx, client/src/pages/Dashboard.jsx, client/src/pages/Find.jsx, server/api.js
=> 81-card provider - Farzaneh

.eslintignore, server/sequelize/migrations/20230813130706-create-calendar.js, server/sequelize/models/calendar.js, server/sequelize/models/index.js
=> #104-calendar model created-Hengameh

client/src/App.js, client/src/Components/Header.jsx, client/src/customHooks/useAuth.js, client/src/pages/Dashboard.jsx, client/src/pages/Find.jsx
Create appContest for state variables
Fixes #108
=> #108 app context karleen

client/src/App.js, client/src/Components/GoogleCalendarForm.js, client/src/Components/Header.jsx, client/src/Mui-Components/HomeCardGrid.jsx, client/src/customHooks/useAuth.js, client/src/pages/Dashboard.jsx, client/src/pages/Find.jsx, client/src/pages/SignUpForm.jsx
add react calendar form and link to cards for find page
Fixes #105
=> #105 calendar form karleen

client/src/Components/Header.jsx, server/api.js
Back end component of the update functionality
Fixes #85
=> 85-Edit backend- Tony Arora

client/src/Components/Newsletter.jsx, client/src/pages/Home.jsx, server/sequelize/config/config.js
=> explicitly define dialect

client/src/customHooks/useAuth.js, server/api.js, server/sequelize/models/calendar.js
=> #123-Heni delete message-Hengameh

client/src/pages/Dashboard.jsx, server/api.js
Dashboard display for customer and provider information once they log in.
Fixes #98
=> 98-Dashboard display- Tony Arora

client/src/index.html
=> Add referrer

client/src/Components/RightSideCard.jsx
=> #131-calender button bug-Hengameh

client/src/Components/GoogleCalendarForm.jsx, client/src/Components/Header.jsx, client/src/Components/Hero.jsx, client/src/Components/HomeCardGrid.jsx, client/src/Components/Newsletter.jsx, client/src/Components/RightSideCard.jsx, client/src/Components/Sidebar.jsx, client/src/Components/StaticGrid.jsx, client/src/pages/Dashboard.jsx, client/src/pages/EditForm.jsx, client/src/pages/SignUpForm.jsx, client/src/pages/Subscription.jsx
=> #102-City and country Field Validation-Hengameh

client/src/Components/Hero.jsx, client/src/Components/HomeCardGrid.jsx, client/src/Components/StaticGrid.jsx
=> Farzaneh-last-please merge
